import { GoogleGenAI } from "@google/genai";

const ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export async function generateMealImage(mealCombo: string): Promise<string> {
  // Client-side check for restricted content
  const restrictedWords = ["sex", "porn", "naked", "nude", "penis", "vagina", "breast", "ass", "butt", "pussy"];
  const lowerMeal = mealCombo.toLowerCase();
  if (restrictedWords.some(word => lowerMeal.includes(word))) {
    throw new Error("INAPPROPRIATE_CONTENT");
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [
          {
            text: `A high-quality, professional food photography shot of a Kenyan meal combo: ${mealCombo}. The meal should look delicious and authentic, served on a plate or in a bowl. Cinematic lighting, 4k resolution, vibrant colors.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    // Log text response if no image was generated
    const textResponse = parts.find(p => p.text)?.text;
    if (textResponse) {
      console.warn("Model returned text instead of image:", textResponse);
    }
    
    throw new Error("No image generated by the model");
  } catch (error) {
    console.error("Error generating image:", error);
    // Fallback to a placeholder if image generation fails
    return `https://picsum.photos/seed/${encodeURIComponent(mealCombo)}/800/800`;
  }
}

export async function generateProfileAvatar(fullname: string): Promise<string> {
  try {
    const response = await ai.models.generateContent({
      model: "gemini-2.5-flash-image",
      contents: {
        parts: [
          {
            text: `A professional, clean, and friendly student avatar for a person named ${fullname}. The style should be like a modern 3D illustration or a high-quality professional headshot. Neutral background, well-lit, suitable for a university profile.`,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    const parts = response.candidates?.[0]?.content?.parts || [];
    for (const part of parts) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    const textResponse = parts.find(p => p.text)?.text;
    if (textResponse) {
      console.warn("Model returned text instead of avatar:", textResponse);
    }

    throw new Error("No avatar generated by the model");
  } catch (error) {
    console.error("Error generating avatar:", error);
    return `https://api.dicebear.com/7.x/avataaars/svg?seed=${encodeURIComponent(fullname)}`;
  }
}

export async function chatWithAssistant(message: string, context: string): Promise<string> {
  // Client-side check for restricted content
  const restrictedWords = ["sex", "porn", "naked", "nude", "penis", "vagina", "breast", "ass", "butt", "pussy"];
  const lowerMessage = message.toLowerCase();
  if (restrictedWords.some(word => lowerMessage.includes(word))) {
    return "INAPPROPRIATE_CONTENT_DETECTED";
  }

  try {
    const response = await ai.models.generateContent({
      model: "gemini-3-flash-preview",
      contents: message,
      config: {
        systemInstruction: `You are the Ulikula? Assistant for MMUST (Masinde Muliro University of Science and Technology) students. 
        Your goal is to help students decide what to eat. 
        Current context of recent posts: ${context}.
        Be friendly, use student slang where appropriate (e.g., 'kibandaski', 'comrades'), and suggest meal combos based on the context or general student favorites like Ugali, Sukuma, Chapati, Beans, etc.
        
        STRICT SAFETY RULE: You are strictly forbidden from generating, responding to, or acknowledging any sexual content, body parts, or inappropriate language. If a user asks for such content, politely decline and remind them that this is a student food community.
        
        Keep responses concise and helpful.`,
      },
    });
    return response.text || "I'm not sure what to say. Maybe try asking about specific meals?";
  } catch (error) {
    console.error("Chat error:", error);
    return "I'm having a bit of a brain freeze. Can you ask that again?";
  }
}
